---
id: coreos-cloudconfig
name: CoreOS host

operating_system: coreos-1053.2.0-stable

unattended:
  type: cloud-config
  use: coreos.yml

metadata:
  root_pass: $1$De/uvwHY$77ZDxv9lNwZJbwFziq4Ix0

validate:
    - image: busybox
      pull: yes
      command: "if [ ! -e /etc ]; then echo 'SOMETHINGS WRONG!!!'; exit 1; fi"
      retry: 0
      timeout: 60


before_shutdown:
      - image: busybox
        pull: yes
        command: /bin/ls
        args:
          - -la
          - /
        retry: 0
        timeout: 60
