#cloud-config
coreos:

  update:
    group: stable
    reboot-strategy: off

  etcd2:
  {{ if eq .host.role "kube-master" }}
    # local master enpoints
    name: {{ .host.mstr }}
    initial-advertise-peer-urls: http://{{.host.ip}}:2380
    advertise-client-urls: http://{{.host.ip}}:2379
    listen-peer-urls: http://0.0.0.0:2380
  {{ else }}
    proxy: on
  {{ end }}

    # cluster endpoints
    listen-client-urls: http://0.0.0.0:2379
    initial-cluster: {{ range $i, $node := .env.etcd_cloud_nodes }}{{ if $i }},{{end}}{{$node.name}}=http://{{$node.ip}}:2380{{end}}

  fleet:
  {{ if index .host "mstr" }}
    metadata: "role={{.host.role}},kube-master={{.host.mstr}},vlan={{.host.interface.vlan}},vlan-{{.host.interface.vlan}}=true{{if index .host "fleetadd"}}{{.host.fleetadd}}{{end}}"
  {{ else }}
    metadata: "role={{.host.role}},vlan={{.host.interface.vlan}},vlan-{{.host.interface.vlan}}=true{{if index .host "fleetadd"}}{{.host.fleetadd}}{{end}}"
  {{ end }}

  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      drop-ins:
        - name: 10-docker-opts.conf
          content: |
            [Service]
            # Setting max log size to 10M
            Environment="DOCKER_OPTS=--log-driver=json-file --log-opt max-size=10m"
    - name: early-docker.service
      drop-ins:
        - name: 10-docker-opts.conf
          content: |
            [Service]
            # Setting max log size to 10M
            Environment="DOCKER_OPTS=--log-driver=json-file --log-opt max-size=10m"

{{ if index .env "ssh_authorized_keys" }}
ssh_authorized_keys:
  {{ range $element := .env.ssh_authorized_keys }}
  - {{$element}}
  {{ end }}
{{ else }}
users:
  - name: core
    passwd: {{ .group.root_pass }}
{{ end }}
