---
ServerAPI:
  Addr: 10.10.10.5
  Port: 24601
  PrivateKey: "functional/test/server.key"
  PublicKey: "functional/test/server.pem"
SavePath: "/var/vaquero/save"
DHCPMode: server
LocalDir:
  PollInterval: 1
SoT:
- Local:
    ID: vaquero-local
    Root: /vagrant/local
Log:
  Level: debug
  Location: stdout
  Type: text
