---
ServerAPI:
  Addr: 10.10.10.5
  Port: 24601
  PrivateKey: "/vaquero/secret/server.key"
  PublicKey: "/vaquero/secret/server.pem"
ServerClient:
  Addr: 10.10.10.5
  Port: 24601
  InsecureSkipVerify: true
SavePath: "/var/vaquero"
LocalDir:
  PollInterval: 1
SoT:
- Local:
    ID: vaquero-local
    Root: /vagrant/local
Log:
  Level: debug
  Location: stdout
  Type: text
