---
ServerApi:
  Address: 10.0.2.15
  Port: 24601
AgentApi:
  InsecureAddr: 10.10.10.5
  InsecurePort: 24604
AssetServer:
  Addr: 10.10.10.5
  Port: 24602
  BaseDir: "/var/vaquero/files"
  Scheme: http
SavePath: "/var/vaquero/save"
DHCPMode: server
LocalDir:
  PollInterval: 1
SoT:
- Local:
    ID: vaquero-local
    Root: /vagrant/local
Log:
  Level: debug
  Location: stdout
  Type: text
