---
ServerAPI:
  Addr: 10.10.10.5
  Port: 24601
  PrivateKey: "/vaquero/secret/server.key"
  PublicKey: "/vaquero/secret/server.pem"
ServerClient:
  Addr: 10.10.10.5
  Port: 24601
  InsecureSkipVerify: true
SavePath: "/var/vaquero"
Etcd:
  Endpoints:
  - "http://10.10.10.5:2379"
  - "http://10.10.10.6:2379"
  - "http://10.10.10.7:2379"
  Timeout: 5
  Retry: 3
LocalDir:
  PollInterval: 1
SoT:
- Local:
    ID: vaquero-local
    Root: /vagrant/local
Log:
  Level: debug
  Location: stdout
  Type: text
