---
AgentApi:
  InsecureAddr: 10.10.10.5
  InsecurePort: 24602
AssetServer:
  Addr: 10.10.10.5
  Port: 8080
  BaseDir: "/var/vaquero/files"
  Scheme: http
SavePath: "/var/vaquero/save"
SoT:
- Local:
    ID: vaquero-local
    Root: /vagrant/local
Log:
  Level: debug
  Location: stdout
  Type: text
