---
ServerApi:
  Address: 10.0.2.15
  Port: 24601
AgentApi:
  InsecureAddr: 10.10.10.5
  InsecurePort: 24602
AssetServer:
  Addr: 10.10.10.5
  Port: 8080
  BaseDir: "/var/vaquero/files"
  Scheme: http
SavePath: "/var/vaquero/save"
DHCPMode: server
DHCPCIDR: "10.10.10.5/24"
Gitter:
  Endpoint: "/postreceive"
  Timeout: 2
  Addr: 10.0.2.15
  Port: 9090
GitHook:
- ID: vaquero-vagrant
  Token: 970328a2f23fb64ddd03293f13dafda9647a0955
  URL: https://github.com/CiscoCloud/vaquero-examples
  Secret: supersecretcode
SoT:
- Git:
    HookID: vaquero-vagrant
    ID: vaquero-vagrant
    Branch: vagrant
Log:
  Level: debug
  Location: stdout
  Type: text
